import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import pruthvi from '../public/myselfN.png'
import Typewriter from 'typewriter-effect';
import About from '../components/About';
import Contact from '../components/Contact';
import Projects from '../components/Projects'
import Experience from '../components/Experience'
import Skills from '../components/Skills'
import { motion } from 'framer-motion'


const inter = Inter({ subsets: ['latin'] })


export default function Home() {

  return (

    <div>

      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section id='home' >
        <main className='flex flex-col lg:flex-row items-center lg:justify-around mx-auto px-10 sm:py-28 md:py-40 md:px-20 lg:px-40 py-20 lg:pt-40' >

          <motion.div className='relative overflow-hidden mx-auto mt-10 bg-gradient-to-b bg-gray-100 rounded-full md:max-w-4xl md:max-h-4xl sm:w-96 sm:h-96 w-80 h-80'
            initial={{ x: -100, opacity: 0 }}
            whileInView={{ x: 0, opacity: 1, }}
            viewport={{ once: false }}
            transition={{ duration: 1 }}
          >
            <Image src={pruthvi} layout="contain" objectFit='contain' alt="default" />
          </motion.div>

          <motion.div
            initial={{ x: 100, opacity: 0 }}
            whileInView={{ x: 0, opacity: 1 }}
            viewport={{ once: false }}
            transition={{ duration: 1 }}
          >
            <div className='text-center p-10'>
              <h2 className='sm:text-4xl md:text-5xl text-3xl py-3 font-semibold font-chivoMono'>Hi,myself Pruthviraj</h2>
              <div className='inline-flex'>
                <h3 className='sm:text-2xl md:text-3xl text-lg py-3 font-bold font-chivoMono'>I&apos;m a</h3>
                <h3 className='sm:text-2xl md:text-3xl text-lg py-3 px-2 font-bold font-chivoMono text-orange-500'>
                  <Typewriter
                    options={{
                      strings: ['Flutter Developer', 'Programmer', 'Problem Solver'],
                      autoStart: true,
                      loop: true,
                    }}
                  />
                </h3>
              </div>
            </div>
            <div>
              <p className='sm:text-lg md:text-xl text-base text-center py-5 leading-6 text-gray-900 font-chivoMono max-w-lg mx-auto dark:text-white'>
                I am currently pursuing B-Tech(3rd Year) in Information Technology from Veermata Jijabai Technological Institute, Mumbai.
                I am passionate about building excellent software that improves the lives of those around me.
              </p>
              <div className='md:px-64 font-chivoMono flex justify-center'>
                <a target='_blank' rel="noreferrer" href='https://drive.google.com/file/d/1H163J3jXfklf_a6DNfVRCE4exwOHHIW1/view?usp=sharing'>
                  <button className='text-center items-center font-bold hover:text-white dark:hover:text-black bg-orange-500 max-w-lg mx-auto leading-6 border-2 border-gray-500 rounded-xl py-2 px-5'>Resume</button>
                </a>
              </div>

            </div>

          </motion.div>
        </main>
      </section>

      <section id='about'>
        <div>
          <About />
        </div>
      </section>


      <section id='experience'>
        <div><Experience /></div>
      </section>
      <section id='skills'>
        <div>
          <Skills />
        </div>
      </section>


      <section id='projects'>
        <div>
          <Projects />
        </div>

      </section>

      <section id='contact'>
        <Contact />
      </section>



    </div >
  )
}
